# Generated by Django 3.2.3 on 2021-08-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='estate_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='number_of_plots',
            field=models.IntegerField(),
        ),
    ]
